name = "MassCommits"
uuid = "4dc75a2a-9676-11e9-1baa-91c449cf283a"
authors = ["Anshul Singhvi"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
